services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: vibeen
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d vibeen"]
      interval: 5s
      timeout: 5s
      retries: 20

  api:
    build:
      context: ./api
    environment:
      NODE_ENV: development
      PORT: 4000
      DATABASE_URL: postgres://app:app@db:5432/vibeen
      JWT_SECRET: change-me
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./api:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:4000/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 40

  web:
    build:
      context: ./web
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:4000
    ports:
      - "5173:5173"
    depends_on:
      api:
        condition: service_healthy
    volumes:
      - ./web:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

volumes:
  db_data:
